version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: doc1_database
    ports:
      - 4321:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=doc1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend:
    image: backend/assignment
    build:
      context: ./
    container_name: doc1_backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:4321/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db:
    driver: local

