apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc1-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc1-database
  template:
    metadata:
      labels:
        app: doc1-database
    spec:
      containers:
      - name: doc1-database
        image: postgres:14.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "doc-db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
