apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/doc1-assignment-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_BACKEND_URL
              value: http://backend:8080
          image: frontend/assignment
          imagePullPolicy: Never
          name: doc1-frontend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: pat
