name: CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-minikube:
    name: Start Minikube
    runs-on: ubuntu-latest
    outputs:
      kubeconfig: ${{ steps.start-minikube.outputs.kubeconfig }}
    steps:
      - name: Set up Minikube
        id: start-minikube
        uses: medyagh/setup-minikube@latest
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status
      - name: Configure kubectl
        run: |
          kubectl config use-context minikube
      - name: Save Kubeconfig
        id: save-kubeconfig
        run: echo "::set-output name=kubeconfig::$(cat ~/.kube/config | base64)"

  build-backend:
    name: Build Backend JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Build JAR
        run: |
          cd Spring
          ./mvnw clean install
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: Spring/target/*.jar

  deploy-backend:
    name: CD Pipeline - Backend
    runs-on: ubuntu-latest
    needs: [start-minikube, build-backend]
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: Spring/target/
      - name: Build Docker Image
        run: |
          cd Spring
          docker build -t backend/assignment .
          echo "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          docker save backend/assignment -o backend.tar
          minikube image load backend.tar
          cd k8s-configs
          kubectl apply -f backend-service.yaml
          kubectl apply -f backend-deployment.yaml
      - name: Test pods
        run: |
          kubectl get pods
      - name: Test service
        run: |
          kubectl get services

  deploy-frontend:
    name: CD Pipeline - Frontend
    runs-on: ubuntu-latest
    needs: start-minikube
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build Docker Image
        run: |
          cd React
          docker build -t frontend/assignment .
          echo "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          docker save frontend/assignment -o frontend.tar
          minikube image load frontend.tar
          cd k8s-configs
          kubectl apply -f frontend-service.yaml
          kubectl apply -f frontend-deployment.yaml
      - name: Test pods
        run: |
          kubectl get pods
      - name: Test service
        run: |
          kubectl get services
