name: CD - Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    name: Build images and deploy to Minikube
    steps:
      - uses: actions/checkout@v4
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Verify cluster
        run: kubectl get pods -A
      
      - name: Build images
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          cd Spring
          docker build -t backend .
          cd ../React
          docker build -t frontend .
          echo -n "Verifying images:"
          docker images
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            agostonbabicz/backend
            agostonbabicz/frontend

      - name: Push backend image to Docker Hub
        id: push_backend
        uses: docker/build-push-action@v4
        with:
          context: ./Spring
          file: ./Spring/Dockerfile
          push: true
          tags: agostonbabicz/backend:latest, agostonbabicz/backend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Push frontend image to Docker Hub
        id: push_frontend
        uses: docker/build-push-action@v4
        with:
          context: ./React
          file: ./React/Dockerfile
          push: true
          tags: agostonbabicz/frontend:latest, agostonbabicz/frontend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation for backend
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: agostonbabicz/backend
          subject-digest: ${{ steps.push_backend.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for frontend
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: agostonbabicz/frontend
          subject-digest: ${{ steps.push_frontend.outputs.digest }}
          push-to-registry: true
      
      - name: Deploy to Minikube
        run: |
          cd deployments
          kubectl apply -f deployment-backend.yaml
          kubectl apply -f deployment-frontend.yaml
      
      - name: Test service URLs
        run: minikube service list
